name: kusuri_mobile_flutter
description: "添付文書 Pocket の モバイルアプリ"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.5.0
  url_launcher: ^6.2.5
  html: ^0.15.4
  http: ^1.1.2
  async: ^2.11.0
  sizer: ^2.0.15
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.9.3
  firebase_analytics: ^10.5.1
  firebase_core: ^2.17.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  connecteo: ^2.2.0
  uuid: ^4.4.0
  logger: ^2.2.0
  collection: ^1.18.0
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  keyboard_actions: ^4.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_01.png
    - assets/images/onboarding_02.png
    - assets/images/onboarding_03.png
    - assets/images/onboarding_04.png
    - assets/database/kusuri.db
